package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA63746)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDADB)
val md_theme_light_onPrimaryContainer = Color(0xFF40000E)
val md_theme_light_secondary = Color(0xFF006A63)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF72F7EA)
val md_theme_light_onSecondaryContainer = Color(0xFF00201D)
val md_theme_light_tertiary = Color(0xFF9C4332)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD3)
val md_theme_light_onTertiaryContainer = Color(0xFF3F0400)
val md_theme_light_error = Color(0xFFA03C49)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDADB)
val md_theme_light_onErrorContainer = Color(0xFF40000E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFEF8FC)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_inverseSurface = Color(0xFF323033)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inversePrimary = Color(0xFFFFB2B7)
val md_theme_light_surfaceTint = Color(0xFFA63746)
val md_theme_light_outlineVariant = Color(0xFFCBC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB2B7)
val md_theme_dark_onPrimary = Color(0xFF66031C)
val md_theme_dark_primaryContainer = Color(0xFF861F31)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDADB)
val md_theme_dark_secondary = Color(0xFF51DBCE)
val md_theme_dark_onSecondary = Color(0xFF003733)
val md_theme_dark_secondaryContainer = Color(0xFF00504A)
val md_theme_dark_onSecondaryContainer = Color(0xFF72F7EA)
val md_theme_dark_tertiary = Color(0xFFFFB4A5)
val md_theme_dark_onTertiary = Color(0xFF5F1609)
val md_theme_dark_tertiaryContainer = Color(0xFF7D2C1D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD3)
val md_theme_dark_error = Color(0xFFFFB2B7)
val md_theme_dark_onError = Color(0xFF630C1E)
val md_theme_dark_errorContainer = Color(0xFF812533)
val md_theme_dark_onErrorContainer = Color(0xFFFFDADB)
val md_theme_dark_outline = Color(0xFF958E99)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF141316)
val md_theme_dark_onSurface = Color(0xFFCAC5CA)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inversePrimary = Color(0xFFA63746)
val md_theme_dark_surfaceTint = Color(0xFFFFB2B7)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFAF3E4D)
